using UnityEngine;
using TMPro;
using System.Collections.Generic;
using System;

public class DropdownScript : MonoBehaviour
{
    public TMP_Dropdown dropdown; // Referência ao TMP_Dropdown (associado ao próprio GameObject)
    public TMP_InputField inputField; // Referência ao TMP_InputField
    private List<String> mapasExemplos = new List<String>();
    //const exampleMaps = [
    //        1["###############\n#@  *    * P I#\n# ### ####### #\n#*#*#  *#  *#*#\n# # ### # # #B#\n#*#*I O*  # #*#\n# #I# ##### ###\n#*#R#  *# #***#\n# ###G#$#*###!#\n# #*  #    I# #\n# #I####O## # #\n# #*  # * I*# #\n# ### #######*#\n# * * #*    * #\n###############", "W;W;W;W;W;W;S;S;E;E;S;S;N;N;W;E;S;S;E;E;N;S;W;E;N;S;W;E;W;W;W;N;W;N;S;E;S;E;E;E;N;S;W;E;W;E;N;N;S;S;W;E;W;E;N;S;W;W;N;S;N;N;W;W;E;E;S;S;E;E;N;N;S;S;W;E;W;W;N;S;W;N;E;N;S;E;E;E;E;E;W;N;S;N;N;S;S;W;S;E;N;S;N;S;E;E;N;N;S;N;E;W;S;S;W;W;N;S;N;N;W;W;N;N;W;W;W;W;E;E;E;E;S;S;E;E;S;S;W;N;S;E;E;E;N;N;E;E;S;S;S;S;E;E;S;N;W;W;N;N;N;N;W;W;S;S;W;W;N;S;W;S;N;W;W;592"],
    //        2["###############\n#*I * *I   R**#\n#I# ####### #G#\n#*  #** # * # #\n##### #*# ### #\n#     #   #I !#\n# O########*###\n# #   * #** * #\n# #B###I#*### #\n#@# **# * #  *#\n# #####*#####O#\n#I#I**# #**I* #\n#*### #*# # #*#\n#    P#$* #* *#\n###############","W;W;W;W;N;N;N;N;N;N;E;N;N;S;S;W;E;S;S;S;W;W;N;S;E;E;N;N;N;N;S;N;N;N;W;W;N;N;S;W;W;E;E;N;S;W;W;S;S;W;E;W;W;S;S;S;S;N;N;N;N;N;W;E;S;E;E;N;N;E;E;N;S;N;N;S;N;S;E;E;S;S;S;N;E;E;E;N;N;E;E;S;S;E;E;N;N;E;E;N;N;E;E;S;N;S;S;S;S;W;295"],
    //        3["###############\n#    P* #    B#\n#I####### # # #\n# #*  #!  # #*#\n#*#I# #*###*# #\n# I*#* ** #*# #\n######### #G# #\n#  *I*@*  #I *#\n# O########## #\n#*#  * I** *#*#\n#*# ### ### #R#\n#     #  *#*# #\n# ##O*# # #*# #\n#  *    #* $* #\n###############","W;W;W;W;S;S;S;E;N;E;E;S;S;N;S;E;E;E;E;S;S;W;W;W;W;W;E;W;W;S;S;E;E;W;E;E;W;W;W;N;N;E;E;E;W;E;E;E;W;W;W;W;W;S;S;N;N;E;E;E;W;E;W;W;W;E;W;S;E;S;E;E;W;W;W;E;N;W;W;E;E;W;N;E;E;E;E;E;E;N;N;W;W;N;N;S;S;E;E;S;S;W;W;W;W;W;E;W;W;W;E;E;W;S;E;S;E;E;N;N;E;E;S;S;E;E;E;E;N;N;N;N;N;N;W;W;E;N;N;N;N;N;N;W;W;W;W;S;S;W;W;S;S;E;557"],
    //        4["###############\n#   I #  I*B*I#\n# ###*#I###*# #\n#*#  *#*  # # #\n# # #*# O #*#*#\n#   # I # * #P#\n### ######### #\n#** # * !*I*# #\n# ###I###*###*#\n#@#R *# * I   #\n# #*#I# #######\n# #   #   #  $#\n#I#*###*#*###O#\n#      *#   IG#\n###############","N;S;S;S;S;S;W;W;W;N;S;W;W;S;S;N;N;S;N;S;S;S;S;W;W;E;W;E;W;W;W;E;E;E;E;W;E;W;E;N;N;E;E;S;N;W;W;N;N;E;E;N;S;W;E;N;S;N;N;W;E;S;S;N;S;N;S;W;W;S;S;S;N;S;N;E;E;W;W;S;N;S;N;S;N;S;S;N;N;S;N;E;W;S;S;W;W;E;W;E;E;N;S;W;W;W;E;W;E;W;W;W;E;W;E;W;E;N;N;S;S;E;E;E;E;N;N;E;W;S;S;W;W;W;W;W;W;N;N;N;S;S;S;E;E;E;E;E;E;N;N;E;E;S;S;E;E;E;N;W;E;N;S;W;S;W;N;N;W;514"],
    //        5["###############\n#*    #I*  P* #\n# # # #*#*#!# #\n# #  G# #I# # #\n# ### #*# # #I#\n# #** # I*#I *#\n#*#I#*O## ###*#\n# # #* B#* I# #\n#*#*####### #*#\n#*#$*** #*  # #\n#*##### # ### #\n# #  *# #*#**I#\n#*#R#*# # #*O*#\n#** #*#@  ***I#\n###############","E;E;S;N;S;N;S;S;N;S;N;S;N;S;S;W;E;W;E;S;N;S;S;S;N;S;S;N;N;N;N;W;E;S;S;S;S;S;S;W;S;N;N;W;S;S;N;E;S;N;S;W;W;E;W;E;W;W;W;W;E;E;E;E;N;E;W;N;N;S;W;W;E;W;S;S;S;N;N;N;E;E;S;E;E;N;N;S;N;S;N;N;N;N;N;N;N;S;N;N;W;W;E;W;E;W;S;N;E;E;S;S;S;S;S;S;S;S;S;W;W;290"],
    //        6["###############\n#* * * B *I * #\n# # # #######I#\n#@I #    *  #R#\n#O###*#####O# #\n#G  #*!*  # # #\n# # #####*#*#*#\n#*# ** *# $ # #\n#*#####*###*#*#\n# #** #** #*II#\n#*#P# ###*# # #\n#   # #*#*#I  #\n# ### # #*### #\n# II    #***I #\n###############","S;W;W;N;N;N;N;N;N;N;N;S;N;N;N;S;S;S;S;S;S;S;S;N;S;N;N;W;E;S;S;E;E;N;N;N;N;N;N;E;N;S;N;N;E;E;S;S;S;S;E;W;N;S;N;S;N;N;E;E;E;E;E;E;S;S;N;N;S;S;E;E;S;S;E;E;E;E;S;S;E;E;290"],
    //        7["###############\n#* IG **   *  #\n### O*#*### #*#\n#   # # II#*  #\n# ###*### ### #\n#*#I *  # * * #\n#I# # # ##### #\n# I # O   I*P #\n### #*#*#####*#\n#**B# #*#I **R#\n# ###*# #*#####\n#  *# # #*# @ #\n#I# # #*#*#*#*#\n#  $*!#* I  #*#\n###############","E;S;S;W;W;E;E;N;N;W;W;W;W;W;W;W;N;N;N;E;E;E;W;S;S;S;S;S;N;S;N;S;N;S;S;E;E;E;N;N;E;E;W;W;S;S;W;W;W;N;N;N;N;S;N;S;N;S;N;N;N;W;W;S;W;E;W;E;W;E;W;W;S;N;E;E;N;E;E;E;E;E;E;W;E;E;W;W;W;W;E;W;E;W;W;S;S;S;S;N;N;S;S;S;S;E;E;E;W;W;W;E;W;E;W;E;W;N;N;N;N;N;N;W;N;S;W;S;S;S;S;S;S;N;N;N;N;N;N;E;E;S;S;S;E;E;S;S;E;E;E;E;E;S;N;S;N;S;S;W;W;W;E;E;E;N;N;W;W;W;W;W;S;N;W;N;S;W;S;S;S;S;S;S;W;W;E;E;N;N;N;N;545"],
    //        8["###################\n#*I* *#* *  # * * #\n# #P# #*# #*##### #\n# #  *# # #I#I *# #\n# # ### #*# # # #*#\n#*# #   #*#O *#I# #\n#*#*#I### ###O# # #\n# #  *# #   #*    #\n# ### # ###B#*###R#\n#     # #*I #  *#*#\n###*### #*### #*# #\n#   *G  # #*#*# #I#\n# #I#####I#*# # # #\n# #*#   #*# #*# **#\n# #*#*# # # #!#####\n# #$# #   #*#  @**#\n# ###*##### ##### #\n#I*I *#  I **I   *#\n###################","S;S;S;S;S;E;E;N;E;E;N;N;N;N;E;E;E;E;S;S;S;S;S;S;E;E;W;W;N;S;E;W;S;S;S;S;S;N;N;N;N;N;E;E;W;W;S;S;S;S;S;S;E;E;W;W;N;N;N;N;N;N;N;N;N;N;N;N;W;W;W;W;S;S;S;S;W;W;S;S;S;W;W;S;S;W;W;S;N;E;E;N;N;S;S;W;E;N;N;E;E;N;N;S;S;W;W;S;S;W;W;S;S;S;S;S;S;N;N;N;N;N;E;E;S;S;S;N;N;N;N;N;E;E;N;N;N;E;E;N;N;N;N;E;E;S;S;S;489"],
    //        9["###################\n#     *  ** #**I  #\n#*# # #####*# #*# #\n# #*#*#I  P*# #  *#\n# # # #*##### ### #\n# #  $#       #   #\n#*###*# ### ### ###\n#*I*# #*   I  #** #\n#*# # #######*#I# #\n# #! *  * # * #* B#\n#*#####*#*# #I### #\n#  ** #G *#I# # OI#\n##### # ###R#*# # #\n#I ***# #I  # * #I#\n#*##### #*####### #\n#*#   * **I @     #\n#O# ###########*#*#\n#     *  I*    ***#\n###################","E;N;N;W;W;W;W;W;W;S;S;S;S;S;S;S;S;E;E;S;S;S;S;S;S;E;E;N;S;N;N;S;N;N;S;W;W;W;W;W;W;S;N;E;E;E;E;E;E;N;N;S;N;N;N;S;N;N;N;S;N;N;N;S;N;S;W;E;N;N;S;N;S;W;W;E;E;N;N;S;N;N;S;N;S;W;W;N;N;N;N;S;N;N;N;S;N;W;E;S;N;S;S;S;S;S;S;E;E;N;S;N;N;S;E;E;W;W;W;W;N;N;N;N;S;S;S;S;E;E;W;E;W;W;N;S;E;E;N;S;W;W;N;N;N;N;N;N;W;W;W;W;E;E;E;E;S;S;S;S;S;S;E;E;N;N;N;N;682"],
    //        10["###################\n#    ***  ***     #\n#*##### ####### #*#\n#* I*@# #   G!  # #\n#I### #P# #O##### #\n# #  *# # # I*  # #\n# #*###I# # #*# #I#\n#*#  *#*# # O*  #*#\n#*### #*#I#*# ###*#\n#*I #  *# * # I* *#\n### ##### ##### #I#\n# **#I$ * # * # #*#\n#R# # ### # # #B#*#\n#*# I *     #*# # #\n#I###########*#*#I#\n#   #  *  *   # #I#\n# #I#*# ####### # #\n#  *  # *  *      #\n###################","N;N;N;E;E;E;E;E;E;E;E;E;E;W;W;S;S;W;W;W;W;S;W;S;S;W;W;S;S;S;S;W;W;W;W;N;S;N;S;W;E;E;E;E;E;N;N;N;S;W;W;W;E;E;E;N;N;S;S;S;S;W;W;W;E;E;E;N;N;N;N;E;E;W;W;S;S;N;N;E;E;N;S;W;W;N;N;N;N;S;S;S;S;S;S;S;S;W;W;W;W;N;S;W;N;N;N;N;W;N;N;N;N;N;E;E;E;W;W;W;S;S;S;S;S;E;S;S;S;S;E;E;E;E;E;E;E;439"],
    //        11["###############\n#*  #   * * * #\n# ###*###*###*#\n# * *   #G  #*#\n# #########I#*#\n#I#I  # **# #I#\n###*# # #*# ###\n#** # P*# # * #\n# #######I###@#\n#  *I  I# * B*#\n#######*# ###I#\n# #!* *   # * #\n#*#R# #####*#I#\n#   #   * $ **#\n###############","W;N;S;N;N;W;E;S;S;E;E;N;N;E;E;S;S;S;S;S;W;E;W;W;E;E;N;N;S;S;W;W;E;W;W;W;S;S;E;W;N;N;W;W;S;N;S;S;W;W;N;S;E;E;N;N;E;E;E;E;W;W;S;N;E;E;E;E;N;N;E;E;E;E;S;S;W;W;W;W;W;W;W;W;N;N;E;E;E;E;N;N;E;E;E;E;N;S;W;W;W;W;S;S;W;W;W;W;W;W;274"],
    //        12["###############\n# *** #  *IR  #\n### # # #####I#\n# B*# * # G*#I#\n# #######$# #@#\n# *  *# I #   #\n# ### # ###*###\n#*  #I#P* * **#\n### #*####### #\n#   # #  I#*I #\n#####*#*# # ###\n#  I *# # # I #\n# #######!###*#\n#  I I* * #* *#\n###############","E;E;E;E;N;N;S;S;N;N;E;E;N;S;W;W;N;N;W;W;S;N;E;E;S;S;E;E;N;N;S;N;W;W;W;W;W;S;S;W;W;E;W;N;N;W;W;S;N;S;S;W;W;S;S;E;E;E;E;S;S;S;S;S;W;W;W;S;S;E;E;E;E;E;E;N;S;W;W;W;W;W;W;N;N;E;E;E;N;N;N;N;N;W;W;W;W;N;N;E;E;N;N;E;E;S;S;E;E;N;N;E;E;E;E;E;S;S;W;W;N;N;W;W;S;S;486"],
    //        13["###############\n#*  $**  *G*I #\n#*####### ### #\n# *  R***     #\n#B########### #\n# I I   #*   @#\n#I# ###*# #####\n#  *#* *#*    #\n#*### ###*###*#\n# #  *#*# #  *#\n#*# ### #*# ###\n# #I  #*# #P *#\n#*###*# # ### #\n#  I I#****  !#\n###############","E;E;S;S;W;W;W;W;N;N;N;N;N;N;N;N;E;E;E;E;N;N;W;W;W;W;N;N;W;W;W;W;W;W;W;E;E;E;E;E;E;E;S;S;W;W;W;W;W;W;W;W;S;S;S;S;207"],
    //        14["###############\n#* I  I*  # * #\n# # ### #I# # #\n#*#*#IR #I* # #\n# # # ###*### #\n#** #  I# #   #\n# ##### # # # #\n#*#***# #I#*# #\n#G#*# #*# # # #\n#  *# * # *!#B#\n### ####### # #\n#*  #**  I# # #\n#I###P#@#I# # #\n#     * # *$  #\n###############","N;E;E;E;W;S;S;W;E;N;N;W;W;E;E;W;E;S;S;W;W;W;W;W;W;N;E;E;N;N;N;N;E;E;S;S;E;E;N;N;N;N;N;S;S;S;W;W;N;N;W;W;S;S;N;S;S;S;W;W;S;E;E;E;E;N;N;E;E;S;S;W;W;W;W;W;W;N;E;E;N;N;W;W;N;N;N;N;E;W;N;N;N;N;E;E;E;E;E;E;S;S;N;S;S;S;N;S;S;E;E;W;W;N;N;N;N;N;W;W;S;S;N;N;E;E;S;S;S;S;S;E;E;S;S;S;S;W;W;N;379"],
    //        15["###############\n#* I#   # @* P#\n#*#*# # #*### #\n#*#*# # * #  *#\n# # #R##### # #\n#*    **#*I* !#\n# ##### # #####\n#     #I#   I #\n# ###*# #*###B#\n# *I  # I #* *#\n###*# #*###*#$#\n#G  #** #  *#*#\n# ####### #*# #\n#  *   *  #* *#\n###############","S;S;S;S;W;W;W;S;S;S;S;N;S;W;N;N;N;W;W;W;W;E;W;E;W;E;W;E;E;E;E;S;S;S;E;N;N;N;N;E;N;N;E;E;S;S;W;E;N;N;W;W;S;S;W;S;S;S;S;W;E;N;N;N;N;E;N;N;E;E;S;S;N;N;N;N;W;W;E;E;S;N;W;W;W;E;E;E;S;S;S;S;W;W;W;S;S;S;S;N;N;E;E;E;S;S;S;N;N;N;W;W;W;S;S;W;N;N;361"],
    //        16["###############\n#* *  ***  $* #\n#I# #######I#*#\n# # *I*   # #*#\n# # ##### #I# #\n# #*  #*B # # #\n#*### # #*#R#*#\n# ! #*I*# # #*#\n# # ##### # #*#\n# # ** I#   # #\n#*#I#*#I# ###*#\n#G# # * #* ***#\n#*# ### #####*#\n# *@I     IP* #\n###############","W;W;W;W;W;W;W;W;N;N;N;N;N;N;N;N;N;N;N;S;S;S;S;S;E;W;N;N;N;N;N;E;E;S;S;E;E;W;W;N;N;S;S;E;E;E;E;E;S;S;S;S;S;S;E;E;N;N;N;N;N;N;W;242"],
    //        17["###############\n#  *#  @  # **#\n# # # ###*# #*#\n#*#*#***# # # #\n###*# # # #*#R#\n# * #*#  *#!#*#\n# ##### ###G#*#\n#P    # #*  # #\n# ### # ##### #\n# * #   # * * #\n###*##### ### #\n#   #* ***B # #\n# ######### # #\n#   *  **$ *# #\n###############","S;S;E;E;S;S;W;W;S;S;E;E;E;E;E;E;E;E;W;W;W;E;E;E;E;W;E;E;N;N;W;W;W;E;E;E;S;S;W;W;W;W;W;W;W;W;E;W;W;W;N;N;E;E;N;N;W;W;N;N;E;E;E;E;S;S;E;E;N;N;N;N;E;E;N;N;N;N;W;W;W;W;S;S;E;E;S;S;S;S;S;S;W;E;W;W;N;N;W;W;W;W;S;S;E;E;S;S;W;W;S;S;E;E;E;E;E;E;E;E;E;E;N;N;W;W;N;N;E;E;E;E;N;N;N;N;N;N;N;N;W;W;S;S;S;S;N;N;N;N;E;E;S;S;S;S;S;S;S;490"],
    //        18["#####################\n#   *   #   * *B    #\n# ##### #*###*### #P#\n#*   * *#*#   # #   #\n# ###*### #*### ### #\n# * #       # **#***#\n# #$######### ###*###\n# # ! * **  #   # *@#\n#*####### # ### # # #\n#   #     #   #*# #*#\n# #*# # ##### # # # #\n#*# # # #** # #*# # #\n# ###*# #*# # # # # #\n#*#  *#*  #***  #   #\n# # ##### ######### #\n#  *#* *#   **  * # #\n# #*### ######### # #\n# #*    #*   *#  *# #\n#*###*# # ### #*### #\n#R* **#   * G #     #\n#####################","S;N;S;S;S;W;W;S;S;N;S;N;S;E;E;W;W;N;S;N;N;E;E;N;N;S;N;S;N;S;N;S;N;S;N;N;N;W;W;W;W;W;E;E;W;E;W;W;W;S;S;W;W;S;S;W;W;W;W;W;E;W;W;N;S;N;S;E;W;N;N;W;W;W;W;S;N;E;E;E;E;W;E;W;W;W;W;S;S;N;N;E;W;E;W;E;W;E;W;S;S;S;S;S;S;S;S;S;S;S;S;E;W;N;S;N;N;N;N;N;N;N;N;N;N;N;N;E;W;E;E;E;W;W;W;S;S;N;N;N;N;S;S;E;E;W;E;W;W;S;S;E;E;S;N;W;W;N;N;S;S;N;N;S;S;E;E;W;W;N;N;N;N;S;S;E;E;E;E;S;S;N;N;W;W;W;W;E;W;E;E;E;W;E;E;S;S;N;N;W;W;W;W;E;E;E;E;E;E;W;W;S;S;E;W;N;N;W;W;W;W;S;S;N;S;N;S;N;S;E;E;S;S;E;W;N;N;W;W;N;N;E;E;E;E;820"],
    //        19["###########################\n# #*  *   * *   #*    #   #\n#*# ### ##### ### # # #*# #\n#* R#*#   **# #* *# #   # #\n# ### ###*# ### ### # ###*#\n# #     * #    *#  *#*#   #\n# # # #*######### ### #*#*#\n#B    # #   **  #* *  # # #\n### ### # ##### # ##### # #\n#*$ #** # # *   #*#  *# # #\n# ### #*#*##### # # # #*#*#\n# # * #*#     # # # #* *# #\n# # ###*# ### # ### #####*#\n# # #*# # **# #*#  *  #***#\n# # #*# ### # # # ###*# ###\n#*  #***#*  # #*# *   ** *#\n##### ###*### #!# ####### #\n#*  #*  #     # #     #*  #\n#*# ### ##### # ##### ### #\n# # * #*  #   #G#   # * # #\n#*# ##### # ### # # ### # #\n# # @ *  P#   #  *# * # # #\n# ########### #######*# # #\n#  * *#*    #    * *# #  *#\n# ### # ###*#*# # # # ###*#\n#          * *#*  * #  * *#\n###########################","W;W;W;W;W;E;E;E;E;E;N;N;W;W;N;N;W;E;W;W;N;N;S;N;N;N;S;S;E;E;W;E;N;N;S;N;N;N;N;N;N;N;N;N;E;E;N;S;N;S;N;S;N;S;N;S;N;N;E;E;S;S;E;W;E;E;E;E;N;N;E;E;W;W;E;W;E;E;W;E;N;N;E;E;E;W;S;S;S;S;W;E;W;W;S;S;E;E;E;E;W;E;W;E;W;W;W;W;N;S;E;E;E;E;N;N;S;S;W;E;W;E;W;E;W;W;W;W;N;S;E;E;E;E;W;E;N;N;S;N;N;N;E;W;E;W;E;W;E;W;E;E;N;S;W;W;E;W;E;W;E;W;E;W;N;S;E;E;W;W;E;W;E;E;W;E;N;N;E;E;S;S;S;N;N;S;S;N;S;S;S;S;N;S;S;S;N;S;S;S;S;S;W;E;W;E;W;E;N;S;W;W;S;S;W;W;W;E;W;E;E;E;N;N;E;E;W;W;S;N;E;E;N;N;S;S;W;W;E;E;N;N;N;N;N;S;S;S;S;S;W;W;S;N;S;N;S;S;N;N;E;W;S;S;W;E;N;N;S;S;W;W;E;E;N;N;E;E;N;N;S;N;N;S;N;N;N;N;S;N;N;S;S;S;N;N;N;N;N;N;S;N;S;N;S;N;S;N;N;N;W;W;S;N;E;E;S;S;N;S;N;N;W;W;E;W;E;E;S;S;S;S;S;S;S;S;S;S;S;S;N;N;N;N;N;N;N;N;N;N;N;N;W;W;S;S;W;W;S;N;N;S;N;S;N;N;S;S;E;E;W;W;N;N;S;S;N;S;E;E;W;W;N;N;W;W;W;W;S;S;W;W;S;S;W;W;W;W;N;N;W;W;W;W;E;E;S;S;N;S;N;S;W;W;W;W;E;E;E;E;N;N;E;W;S;N;E;W;W;E;S;S;W;E;W;W;W;W;E;W;E;E;S;N;E;W;W;W;S;S;N;S;N;S;N;N;E;E;E;W;W;W;E;E;E;E;N;S;W;W;W;W;S;S;W;W;E;E;N;N;W;W;S;S;S;S;N;S;N;S;W;E;N;S;N;S;N;S;N;S;N;N;N;N;E;E;E;W;S;S;N;N;E;E;E;E;N;N;E;E;S;S;E;E;E;E;N;N;E;E;N;N;E;E;E;E;S;S;E;E;N;N;E;E;S;S;S;S;S;S;S;S;S;S;S;S;W;W;S;S;E;E;S;S;S;S;S;S;S;S;S;S;W;W;W;W;N;N;N;N;W;W;N;N;W;W;S;S;W;W;N;N;N;N;N;S;S;S;S;S;E;E;N;N;E;E;S;S;E;E;S;S;S;S;E;E;E;E;N;N;N;N;N;N;N;N;N;N;W;W;N;N;E;E;N;N;N;N;N;N;N;N;N;N;N;N;W;W;S;S;W;W;N;N;W;W;W;W;S;S;W;W;S;S;W;W;W;W;N;N;W;W;W;W;N;N;W;W;W;W;S;S;W;W;S;2243"],
    //        20["###############################\n#    * *  * # * * **  #       #\n# # #######*# #######*# ##### #\n#* *  *   #   #  *  * # #** # #\n##### ### # ### ####### # # #*#\n#     #  *# * #* *  **  #*#*# #\n#*# ### #*### # #######*#*# # #\n#*#     # #   #   #   # #*#** #\n#*#######*# ### #*# # # # # ###\n#   # *  *#**   # **#*#*# #* *#\n### #*#######*#######*# # ### #\n#* *#  *#R*        *#*  #   # #\n# #####*# #########@# # ### # #\n#   #   * #        *# #  *  # #\n### #*### # ######### ####### #\n#   #**   #  *  # * # #   #  *#\n# ##### ####### # #$# # # # # #\n#*#   #*** *  #*#  *  #   # # #\n#*#*# ####### # ##### #*###*# #\n# * #     #*  #     #   #*  # #\n# ####### # ####### ### # ### #\n#*#P  *** #     #   #** # #   #\n# # # ###*##### # # # ### # ###\n# * #*#   #  *#*# # #   #     #\n### # # ### # # # # ### #####*#\n#* *#*# #B *#*# * #   #       #\n# ### # # ###*####### # ##### #\n# #  **G#   #*    **#**!# * # #\n# # ##### # ####### #####*# # #\n#*              *  *  *** #  *#\n###############################","E;E;S;S;S;S;S;S;W;W;S;S;E;E;E;E;E;E;E;E;E;E;W;W;W;W;N;N;S;S;E;E;E;E;E;E;E;E;E;E;E;E;E;E;E;E;N;N;E;E;S;S;E;E;N;N;N;N;W;W;W;E;W;W;W;W;S;S;W;W;N;N;W;W;N;S;N;S;N;S;E;E;S;S;N;N;W;W;N;N;N;S;N;N;N;N;S;S;W;W;S;N;E;E;N;N;W;W;W;E;W;E;W;W;N;N;N;N;W;W;W;E;W;E;W;E;W;E;W;W;N;N;S;S;E;E;E;E;S;S;S;S;E;E;E;E;S;S;S;S;S;S;E;E;S;S;E;E;N;N;N;N;S;S;E;E;E;E;E;E;S;S;N;N;W;W;E;E;S;S;S;S;W;E;N;N;N;N;W;W;E;E;S;S;S;N;N;N;W;W;W;W;W;W;N;N;S;S;E;E;E;E;W;W;W;W;S;S;N;N;E;E;E;E;W;W;W;W;N;N;S;S;S;S;W;W;E;E;N;N;N;N;W;W;N;N;E;W;S;S;E;E;S;S;E;W;S;S;W;W;N;N;W;W;N;N;N;S;S;S;E;E;S;S;E;E;N;N;E;E;E;E;E;W;W;W;W;W;N;N;W;W;N;N;S;S;E;E;S;S;S;S;W;W;N;N;W;W;E;E;S;S;E;E;N;N;N;N;W;W;N;N;E;E;W;W;S;N;E;E;N;N;W;W;E;E;S;N;W;W;N;N;N;N;N;N;S;S;S;S;W;W;N;S;E;E;S;S;E;E;W;W;N;S;E;E;S;S;W;W;E;E;N;N;S;S;W;W;S;S;E;E;S;S;E;E;E;E;E;E;S;S;S;N;N;N;W;W;W;W;W;W;S;S;W;W;N;N;W;W;N;N;N;S;S;S;E;E;S;S;E;W;N;N;W;W;N;N;N;N;N;N;W;W;W;W;N;N;N;N;W;W;W;W;N;N;E;E;E;E;E;E;E;E;N;S;W;W;W;W;W;W;W;W;S;S;E;E;E;E;S;S;S;S;E;E;E;E;S;S;W;W;S;S;S;S;W;W;1219"]]


    void Start()
    {

        // Obtém o componente TMP_Dropdown automaticamente (caso o script esteja no mesmo GameObject)
        dropdown = GetComponent<TMP_Dropdown>();

        // Criando uma lista de opções de "MAPA 01" até "MAPA 20"
        List<string> opcoes = new List<string>();
        opcoes.Add("MAPAS");
        for (int i = 1; i <= 20; i++)
        {
            opcoes.Add($"MAPA {i:D2}"); // Formata para sempre ter dois dígitos (ex: "MAPA 01")
        }

        // Limpa as opções atuais e adiciona as novas
        dropdown.ClearOptions();
        dropdown.AddOptions(opcoes);

        InicializarMapas(mapasExemplos);

        // Adiciona um listener para chamar a função quando o valor do dropdown mudar
        dropdown.onValueChanged.AddListener(AtualizarInput);
    }
    void InicializarMapas(List<String> mapasExemplos)
    {
        mapasExemplos.Add("###############\n#@  *    * P I#\n# ### ####### #\n#*#*#  *#  *#*#\n# # ### # # #B#\n#*#*I O*  # #*#\n# #I# ##### ###\n#*#R#  *# #***#\n# ###G#$#*###!#\n# #*  #    I# #\n# #I####O## # #\n# #*  # * I*# #\n# ### #######*#\n# * * #*    * #\n###############");
        mapasExemplos.Add("###############\n#*I * *I   R**#\n#I# ####### #G#\n#*  #** # * # #\n##### #*# ### #\n#     #   #I !#\n# O########*###\n# #   * #** * #\n# #B###I#*### #\n#@# **# * #  *#\n# #####*#####O#\n#I#I**# #**I* #\n#*### #*# # #*#\n#    P#$* #* *#\n###############");
        mapasExemplos.Add("###############\n#    P* #    B#\n#I####### # # #\n# #*  #!  # #*#\n#*#I# #*###*# #\n# I*#* ** #*# #\n######### #G# #\n#  *I*@*  #I *#\n# O########## #\n#*#  * I** *#*#\n#*# ### ### #R#\n#     #  *#*# #\n# ##O*# # #*# #\n#  *    #* $* #\n###############");
        mapasExemplos.Add("###############\n#   I #  I*B*I#\n# ###*#I###*# #\n#*#  *#*  # # #\n# # #*# O #*#*#\n#   # I # * #P#\n### ######### #\n#** # * !*I*# #\n# ###I###*###*#\n#@#R *# * I   #\n# #*#I# #######\n# #   #   #  $#\n#I#*###*#*###O#\n#      *#   IG#\n###############");
        mapasExemplos.Add("###############\n#*    #I*  P* #\n# # # #*#*#!# #\n# #  G# #I# # #\n# ### #*# # #I#\n# #** # I*#I *#\n#*#I#*O## ###*#\n# # #* B#* I# #\n#*#*####### #*#\n#*#$*** #*  # #\n#*##### # ### #\n# #  *# #*#**I#\n#*#R#*# # #*O*#\n#** #*#@  ***I#\n###############");
        mapasExemplos.Add("###############\n#* * * B *I * #\n# # # #######I#\n#@I #    *  #R#\n#O###*#####O# #\n#G  #*!*  # # #\n# # #####*#*#*#\n#*# ** *# $ # #\n#*#####*###*#*#\n# #** #** #*II#\n#*#P# ###*# # #\n#   # #*#*#I  #\n# ### # #*### #\n# II    #***I #\n###############");
        mapasExemplos.Add("###############\n#* IG **   *  #\n### O*#*### #*#\n#   # # II#*  #\n# ###*### ### #\n#*#I *  # * * #\n#I# # # ##### #\n# I # O   I*P #\n### #*#*#####*#\n#**B# #*#I **R#\n# ###*# #*#####\n#  *# # #*# @ #\n#I# # #*#*#*#*#\n#  $*!#* I  #*#\n###############");
        mapasExemplos.Add("###################\n#*I* *#* *  # * * #\n# #P# #*# #*##### #\n# #  *# # #I#I *# #\n# # ### #*# # # #*#\n#*# #   #*#O *#I# #\n#*#*#I### ###O# # #\n# #  *# #   #*    #\n# ### # ###B#*###R#\n#     # #*I #  *#*#\n###*### #*### #*# #\n#   *G  # #*#*# #I#\n# #I#####I#*# # # #\n# #*#   #*# #*# **#\n# #*#*# # # #!#####\n# #$# #   #*#  @**#\n# ###*##### ##### #\n#I*I *#  I **I   *#\n###################");
        mapasExemplos.Add("###################\n#     *  ** #**I  #\n#*# # #####*# #*# #\n# #*#*#I  P*# #  *#\n# # # #*##### ### #\n# #  $#       #   #\n#*###*# ### ### ###\n#*I*# #*   I  #** #\n#*# # #######*#I# #\n# #! *  * # * #* B#\n#*#####*#*# #I### #\n#  ** #G *#I# # OI#\n##### # ###R#*# # #\n#I ***# #I  # * #I#\n#*##### #*####### #\n#*#   * **I @     #\n#O# ###########*#*#\n#     *  I*    ***#\n###################");
        mapasExemplos.Add("###################\n#    ***  ***     #\n#*##### ####### #*#\n#* I*@# #   G!  # #\n#I### #P# #O##### #\n# #  *# # # I*  # #\n# #*###I# # #*# #I#\n#*#  *#*# # O*  #*#\n#*### #*#I#*# ###*#\n#*I #  *# * # I* *#\n### ##### ##### #I#\n# **#I$ * # * # #*#\n#R# # ### # # #B#*#\n#*# I *     #*# # #\n#I###########*#*#I#\n#   #  *  *   # #I#\n# #I#*# ####### # #\n#  *  # *  *      #\n###################");
        mapasExemplos.Add("###############\n#*  #   * * * #\n# ###*###*###*#\n# * *   #G  #*#\n# #########I#*#\n#I#I  # **# #I#\n###*# # #*# ###\n#** # P*# # * #\n# #######I###@#\n#  *I  I# * B*#\n#######*# ###I#\n# #!* *   # * #\n#*#R# #####*#I#\n#   #   * $ **#\n###############");
        mapasExemplos.Add("###############\n# *** #  *IR  #\n### # # #####I#\n# B*# * # G*#I#\n# #######$# #@#\n# *  *# I #   #\n# ### # ###*###\n#*  #I#P* * **#\n### #*####### #\n#   # #  I#*I #\n#####*#*# # ###\n#  I *# # # I #\n# #######!###*#\n#  I I* * #* *#\n###############");
        mapasExemplos.Add("###############\n#*  $**  *G*I #\n#*####### ### #\n# *  R***     #\n#B########### #\n# I I   #*   @#\n#I# ###*# #####\n#  *#* *#*    #\n#*### ###*###*#\n# #  *#*# #  *#\n#*# ### #*# ###\n# #I  #*# #P *#\n#*###*# # ### #\n#  I I#****  !#\n###############");
        mapasExemplos.Add("###############\n#* I  I*  # * #\n# # ### #I# # #\n#*#*#IR #I* # #\n# # # ###*### #\n#** #  I# #   #\n# ##### # # # #\n#*#***# #I#*# #\n#G#*# #*# # # #\n#  *# * # *!#B#\n### ####### # #\n#*  #**  I# # #\n#I###P#@#I# # #\n#     * # *$  #\n###############");
        mapasExemplos.Add("###############\n#* I#   # @* P#\n#*#*# # #*### #\n#*#*# # * #  *#\n# # #R##### # #\n#*    **#*I* !#\n# ##### # #####\n#     #I#   I #\n# ###*# #*###B#\n# *I  # I #* *#\n###*# #*###*#$#\n#G  #** #  *#*#\n# ####### #*# #\n#  *   *  #* *#\n###############");
        mapasExemplos.Add("###############\n#* *  ***  $* #\n#I# #######I#*#\n# # *I*   # #*#\n# # ##### #I# #\n# #*  #*B # # #\n#*### # #*#R#*#\n# ! #*I*# # #*#\n# # ##### # #*#\n# # ** I#   # #\n#*#I#*#I# ###*#\n#G# # * #* ***#\n#*# ### #####*#\n# *@I     IP* #\n###############");
        mapasExemplos.Add("###############\n#  *#  @  # **#\n# # # ###*# #*#\n#*#*#***# # # #\n###*# # # #*#R#\n# * #*#  *#!#*#\n# ##### ###G#*#\n#P    # #*  # #\n# ### # ##### #\n# * #   # * * #\n###*##### ### #\n#   #* ***B # #\n# ######### # #\n#   *  **$ *# #\n###############");
        mapasExemplos.Add("#####################\n#   *   #   * *B    #\n# ##### #*###*### #P#\n#*   * *#*#   # #   #\n# ###*### #*### ### #\n# * #       # **#***#\n# #$######### ###*###\n# # ! * **  #   # *@#\n#*####### # ### # # #\n#   #     #   #*# #*#\n# #*# # ##### # # # #\n#*# # # #** # #*# # #\n# ###*# #*# # # # # #\n#*#  *#*  #***  #   #\n# # ##### ######### #\n#  *#* *#   **  * # #\n# #*### ######### # #\n# #*    #*   *#  *# #\n#*###*# # ### #*### #\n#R* **#   * G #     #\n#####################");
        mapasExemplos.Add("###########################\n# #*  *   * *   #*    #   #\n#*# ### ##### ### # # #*# #\n#* R#*#   **# #* *# #   # #\n# ### ###*# ### ### # ###*#\n# #     * #    *#  *#*#   #\n# # # #*######### ### #*#*#\n#B    # #   **  #* *  # # #\n### ### # ##### # ##### # #\n#*$ #** # # *   #*#  *# # #\n# ### #*#*##### # # # #*#*#\n# # * #*#     # # # #* *# #\n# # ###*# ### # ### #####*#\n# # #*# # **# #*#  *  #***#\n# # #*# ### # # # ###*# ###\n#*  #***#*  # #*# *   ** *#\n##### ###*### #!# ####### #\n#*  #*  #     # #     #*  #\n#*# ### ##### # ##### ### #\n# # * #*  #   #G#   # * # #\n#*# ##### # ### # # ### # #\n# # @ *  P#   #  *# * # # #\n# ########### #######*# # #\n#  * *#*    #    * *# #  *#\n# ### # ###*#*# # # # ###*#\n#          * *#*  * #  * *#\n###########################");
        mapasExemplos.Add("###############################\n#    * *  * # * * **  #       #\n# # #######*# #######*# ##### #\n#* *  *   #   #  *  * # #** # #\n##### ### # ### ####### # # #*#\n#     #  *# * #* *  **  #*#*# #\n#*# ### #*### # #######*#*# # #\n#*#     # #   #   #   # #*#** #\n#*#######*# ### #*# # # # # ###\n#   # *  *#**   # **#*#*# #* *#\n### #*#######*#######*# # ### #\n#* *#  *#R*        *#*  #   # #\n# #####*# #########@# # ### # #\n#   #   * #        *# #  *  # #\n### #*### # ######### ####### #\n#   #**   #  *  # * # #   #  *#\n# ##### ####### # #$# # # # # #\n#*#   #*** *  #*#  *  #   # # #\n#*#*# ####### # ##### #*###*# #\n# * #     #*  #     #   #*  # #\n# ####### # ####### ### # ### #\n#*#P  *** #     #   #** # #   #\n# # # ###*##### # # # ### # ###\n# * #*#   #  *#*# # #   #     #\n### # # ### # # # # ### #####*#\n#* *#*# #B *#*# * #   #       #\n# ### # # ###*####### # ##### #\n# #  **G#   #*    **#**!# * # #\n# # ##### # ####### #####*# # #\n#*              *  *  *** #  *#\n###############################");
    }

    void AtualizarInput(int index)
    {
        // Define o texto do TMP_InputField com base na opção selecionada do TMP_Dropdown
        if (inputField != null && index != 0)
        {
            inputField.text = mapasExemplos[index-1];
        }
        Debug.Log(index);
    }

}
